[project]
name = "helpbot"
version = "0.1.0"
description = "Бот-помощник"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.21.0",
    "aioodbc>=0.5.0",
    "apscheduler>=3.11.0",
    "betterlogging>=1.0.0",
    "environs>=14.2.0",
    "pytz>=2025.2",
    "redis>=6.2.0",
    "sqlalchemy>=2.0.41",
]
